version: '3.8'

services:
  # Core Infrastructure
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fraud-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        transactions.raw:3:1,
        alerts.rule.high_value:3:1,
        alerts.rule.velocity:3:1,
        alerts.rule.impossible_travel:3:1,
        alerts.ml.v1:3:1
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fraud-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - fraud-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    networks:
      - fraud-net

  # Fraud Detection Services
  fraud-detection:
    build:
      context: ./spark-job
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - ML_MODEL_PATH=/app/ml-training/model.pkl
      - SPARK_MASTER=local[*]
    depends_on:
      - kafka
    volumes:
      - ./ml-training:/app/ml-training:ro
    networks:
      - fraud-net
    restart: unless-stopped
    # Increase memory limits for LightGBM
    deploy:
      resources:
        limits:
          memory: 2G

  alert-aggregator:
    build:
      context: ./alert-aggregator
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - KAFKA_CONSUMER_GROUP=es-aggregator
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INDEX=fraud-alerts
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - fraud-net
    restart: unless-stopped

  # Transaction Producer (for testing)
  transaction-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP=kafka:9094
      - TRANSACTIONS_PER_SECOND=5
      - FRAUD_RATE=0.1
    depends_on:
      - kafka
    networks:
      - fraud-net
    profiles:
      - testing

volumes:
  es_data:

networks:
  fraud-net:
    driver: bridge
