version: '3.8'

services:
  # Core Infrastructure
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fraud-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        transactions.raw:3:1,
        alerts.high_value:3:1,
        alerts.velocity:3:1,
        alerts.impossible_travel:3:1,
        alerts.ml.v1:3:1
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fraud-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - fraud-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    networks:
      - fraud-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
      - PIPELINE_WORKERS=1  # required for aggregate plugin
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "5044:5044" # (optional Beats input if you extend later)
    networks:
      - fraud-net

  fraud-detection:
    build:
      context: ./spark-job
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - ML_MODEL_PATH=/app/model.onnx
      - SPARK_MASTER=local[*]
    depends_on:
      - kafka
    networks:
      - fraud-net
    restart: unless-stopped

  transaction-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP=kafka:9094
      - TRANSACTIONS_PER_SECOND=1
      - FRAUD_RATE=0.8
    depends_on:
      - kafka
    networks:
      - fraud-net
    profiles:
      - testing

volumes:
  es_data:

networks:
  fraud-net:
    driver: bridge